-- Triggers to save values before delete from main tables into backup tables

-- Trigger for CUSTOMERS table
CREATE OR REPLACE TRIGGER CUSTOMERS_DELETE_TRIGGER
BEFORE DELETE ON CUSTOMERS
FOR EACH ROW
BEGIN
    INSERT INTO CUSTOMERS_BACKUP VALUES (
        :OLD.CUSTOMER_NAME, 
        :OLD.CUSTOMER_ID, 
        :OLD.PHONE_NO, 
        :OLD.EMAIL, 
        :OLD.ADDRESS, 
        :OLD.USER_NAME, 
        :OLD.PASSWORD, 
        :OLD.GENDER, 
        :OLD.IS_NEW
    );
END;
/


-- Trigger for REVIEW table
CREATE OR REPLACE TRIGGER REVIEW_DELETE_TRIGGER
BEFORE DELETE ON REVIEW
FOR EACH ROW
BEGIN
    INSERT INTO REVIEW_BACKUP VALUES (
        :OLD.CUSTOMER_ID, 
        :OLD.CUSTOMER_NAME, 
        :OLD.REVIEW_ID, 
        :OLD.COMMENTS
    );
END;
/

-- Trigger for TOUR_PACKAGES table
CREATE OR REPLACE TRIGGER TOUR_PACKAGES_DELETE_TRIGGER
BEFORE DELETE ON TOUR_PACKAGES
FOR EACH ROW
BEGIN
    INSERT INTO TOUR_PACKAGES_BACKUP VALUES (
        :OLD.PACKAGE_ID, 
        :OLD.DAY, 
        :OLD.NIGHT, 
        :OLD.COST, 
        :OLD.RATING, 
        :OLD.CURRENT_CAPACITY, 
        :OLD.SPOT_ID
    );
END;
/

-- Trigger for TOUR_SPOT table
CREATE OR REPLACE TRIGGER TOUR_SPOT_DELETE_TRIGGER
BEFORE DELETE ON TOUR_SPOT
FOR EACH ROW
BEGIN
    INSERT INTO TOUR_SPOT_BACKUP VALUES (
        :OLD.SPOT_ID, 
        :OLD.LOCATION, 
        :OLD.NAME, 
        :OLD.SEASON
    );
END;
/

-- Trigger for HOTELS table
CREATE OR REPLACE TRIGGER HOTELS_DELETE_TRIGGER
BEFORE DELETE ON HOTELS
FOR EACH ROW
BEGIN
    INSERT INTO HOTELS_BACKUP VALUES (
        :OLD.NAME, 
        :OLD.HOTEL_ID, 
        :OLD.PACKAGE_ID, 
        :OLD.LOCATION, 
        :OLD.RATING
    );
END;
/

-- Trigger for ROOMS table
CREATE OR REPLACE TRIGGER ROOMS_DELETE_TRIGGER
BEFORE DELETE ON ROOMS
FOR EACH ROW
BEGIN
    INSERT INTO ROOMS_BACKUP VALUES (
        :OLD.ROOM_ID, 
        :OLD.TYPE, 
        :OLD.HOTEL_ID
    );
END;
/

-- Trigger for PAYMENT table
CREATE OR REPLACE TRIGGER PAYMENT_DELETE_TRIGGER
BEFORE DELETE ON PAYMENT
FOR EACH ROW
BEGIN
    INSERT INTO PAYMENT_BACKUP VALUES (
        :OLD.PAYMENT_ID, 
        :OLD.PAYMENT_MEDIA, 
        :OLD.AMOUNT, 
        :OLD.PAID_UNPAID_STATUS, 
        :OLD.DUE
    );
END;
/

-- Trigger for RESERVATION table
CREATE OR REPLACE TRIGGER RESERVATION_DELETE_TRIGGER
BEFORE DELETE ON RESERVATION
FOR EACH ROW
BEGIN
    INSERT INTO RESERVATION_BACKUP VALUES (
        :OLD.RESERVATION_ID, 
        :OLD.RESERVATION_DATE, 
        :OLD.STATUS, 
        :OLD.CUSTOMER_ID, 
        :OLD.PAYMENT_ID, 
        :OLD.PACKAGE_ID
    );
END;
/

-- Trigger for ADMIN table
CREATE OR REPLACE TRIGGER ADMIN_DELETE_TRIGGER
BEFORE DELETE ON ADMIN
FOR EACH ROW
BEGIN
    INSERT INTO ADMIN_BACKUP VALUES (
        :OLD.ADMIN_ID, 
        :OLD.USER_NAME, 
        :OLD.PASSWORD
    );
END;
/

-- Trigger for TOUR_INFORMATION table
CREATE OR REPLACE TRIGGER TOUR_INFORMATION_DELETE_TRIGGER
BEFORE DELETE ON TOUR_INFORMATION
FOR EACH ROW
BEGIN
    INSERT INTO TOUR_INFORMATION_BACKUP VALUES (
        :OLD.SPOT_NAME, 
        :OLD.SPOT_INFO, 
        :OLD.IMAGE_LINK, 
        :OLD.SPOT_ID
    );
END;
/

-- Trigger for RATING_COUNT table
CREATE OR REPLACE TRIGGER RATING_COUNT_DELETE_TRIGGER
BEFORE DELETE ON RATING_COUNT
FOR EACH ROW
BEGIN
    INSERT INTO RATING_COUNT_BACKUP VALUES (
        :OLD.PACKAGE_ID, 
        :OLD.COUNT
    );
END;
/
