CREATE TABLE CUSTOMERS_BACKUP (
    CUSTOMER_NAME CHAR(50),
    CUSTOMER_ID NUMBER(7),
    PHONE_NO CHAR(11),
    EMAIL CHAR(50),
    ADDRESS VARCHAR2(100),
    USER_NAME CHAR(20),
    PASSWORD VARCHAR2(20), 
    GENDER CHAR(1),
    IS_NEW CHAR(1)
);

CREATE TABLE CUSTOMER_RATING_BACKUP (
    CUSTOMER_ID NUMBER(7),
    RATING_ID NUMBER (7),
    STAR NUMBER(1)
);

CREATE TABLE REVIEW_BACKUP (
    CUSTOMER_ID NUMBER(7),
    CUSTOMER_NAME VARCHAR2(100),
    REVIEW_ID NUMBER(7),
    COMMENTS VARCHAR2(400)
);

CREATE TABLE TOUR_PACKAGES_BACKUP (
    PACKAGE_ID NUMBER(7),
    DAY NUMBER(1),
    NIGHT NUMBER(1),
    COST NUMBER(7, 2),
    RATING NUMBER(3, 2),
    CURRENT_CAPACITY NUMBER(4),
    SPOT_ID NUMBER (7)
);

CREATE TABLE TOUR_SPOT_BACKUP (
    SPOT_ID NUMBER (7),
    LOCATION CHAR(100),
    NAME CHAR(50),
    SEASON CHAR(40)
);

CREATE TABLE HOTELS_BACKUP (
    NAME VARCHAR2(100),
    HOTEL_ID NUMBER(7),
    PACKAGE_ID NUMBER (7),
    LOCATION VARCHAR2(100),
    RATING NUMBER(1)
);

CREATE TABLE ROOMS_BACKUP (
    ROOM_ID NUMBER(4),
    TYPE VARCHAR2(50),
    HOTEL_ID NUMBER(7)
);

CREATE TABLE PAYMENT_BACKUP (
    PAYMENT_ID NUMBER(7),
    PAYMENT_MEDIA VARCHAR2(20),
    AMOUNT NUMBER(10, 2),
    PAID_UNPAID_STATUS CHAR(6),
    DUE NUMBER(10, 2)
);

CREATE TABLE RESERVATION_BACKUP (
    RESERVATION_ID NUMBER(7),
    RESERVATION_DATE DATE,
    STATUS VARCHAR2(20),
    CUSTOMER_ID NUMBER(7),
    PAYMENT_ID NUMBER(7),
    PACKAGE_ID NUMBER(7)
);

CREATE TABLE ADMIN_BACKUP (
    ADMIN_ID NUMBER(7),
    USER_NAME VARCHAR(50),
    PASSWORD VARCHAR(100)
);

CREATE TABLE TOUR_INFORMATION_BACKUP (
    SPOT_NAME VARCHAR2(50),
    SPOT_INFO VARCHAR2(900),
    IMAGE_LINK VARCHAR2(40),
    SPOT_ID NUMBER(7)
);

CREATE TABLE RATING_COUNT_BACKUP (
    PACKAGE_ID NUMBER(7),
    COUNT NUMBER
);