CREATE TABLE CUSTOMERS (
    CUSTOMER_NAME CHAR(50),
    CUSTOMER_ID NUMBER(7),
    PHONE_NO CHAR(11),
    EMAIL CHAR(50),
    ADDRESS VARCHAR2(100),
    USER_NAME CHAR(20),
    PASSWORD VARCHAR2(20), 
    GENDER CHAR(1),
    IS_NEW CHAR(1),
    PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT CHK_PHONE_NO CHECK (LENGTH(TO_CHAR(PHONE_NO)) = 11)
);


CREATE TABLE CUSTOMER_RATING(
CUSTOMER_ID NUMBER(7),
RATING_ID NUMBER (7),
STAR NUMBER(1),
PRIMARY KEY ( RATING_ID),
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMERS(CUSTOMER_ID)
ON DELETE SET NULL
);


CREATE TABLE REVIEW (
    CUSTOMER_ID NUMBER(7),
		CUSTOMER_NAME VARCHAR2(100),
    REVIEW_ID NUMBER(7),
    COMMENTS VARCHAR2(400),
    PRIMARY KEY (REVIEW_ID),
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMERS(CUSTOMER_ID)
    ON DELETE SET NULL
);


CREATE TABLE TOUR_PACKAGES (
    PACKAGE_ID NUMBER(7),
    DAY NUMBER(1),
    NIGHT NUMBER(1),
    COST NUMBER(7, 2),
    RATING NUMBER(3, 2),
    CURRENT_CAPACITY NUMBER(4),
    SPOT_ID NUMBER (7),
    PRIMARY KEY(PACKAGE_ID),
		FOREIGN KEY(SPOT_ID)
    REFERENCES TOUR_SPOT(SPOT_ID),
    CONSTRAINT CHK_RATING CHECK (RATING BETWEEN 1 AND 5),
    CONSTRAINT CHK_DAYS CHECK (DAY <= 7)
);


CREATE TABLE TOUR_SPOT(
SPOT_ID NUMBER (7),
LOCATION CHAR(100),
NAME CHAR(50),
SEASON CHAR(40),
PRIMARY KEY (SPOT_ID),

);

CREATE TABLE HOTELS(
NAME VARCHAR2(100),
HOTEL_ID NUMBER(7),
PACKAGE_ID NUMBER (7),
LOCATION VARCHAR2(100),
RATING NUMBER(1),
PRIMARY KEY(HOTEL_ID),
FOREIGN KEY (PACKAGE_ID)
REFERENCES TOUR_PACKAGES(PACKAGE_ID)
ON DELETE SET NULL

);
CREATE TABLE ROOMS(
ROOM_ID NUMBER(4),
TYPE VARCHAR2(50),
HOTEL_ID NUMBER(7),
PRIMARY KEY (HOTEL_ID, ROOM_ID),
FOREIGN KEY (HOTEL_ID)
REFERENCES HOTELS(HOTEL_ID)
ON DELETE SET NULL
);
CREATE TABLE PAYMENT (
    PAYMENT_ID NUMBER(7),
    PAYMENT_MEDIA VARCHAR2(20),
    AMOUNT NUMBER(10, 2),
    PAID_UNPAID_STATUS CHAR(6),
    DUE NUMBER(10, 2),
    PRIMARY KEY(PAYMENT_ID)
);


CREATE TABLE RESERVATION(
RESERVATION_ID NUMBER(7),
RESERVATION_DATE DATE,
STATUS VARCHAR2(20),
CUSTOMER_ID NUMBER(7),
PAYMENT_ID NUMBER(7),
PACKAGE_ID NUMBER(7), 
PRIMARY KEY(RESERVATION_ID),
FOREIGN KEY(PAYMENT_ID)
REFERENCES PAYMENT(PAYMENT_ID),
FOREIGN KEY(PACKAGE_ID)
REFERENCES TOUR_PACKAGES(PACKAGE_ID),
FOREIGN KEY(CUSTOMER_ID)
REFERENCES CUSTOMERS(CUSTOMER_ID)
ON DELETE SET NULL

);

CREATE TABLE ADMIN (
    ADMIN_ID NUMBER(7),
    USER_NAME VARCHAR(50),
    PASSWORD VARCHAR(100), 
    PRIMARY KEY(ADMIN_ID),
    CONSTRAINT CHK_ADMIN_ID CHECK (ADMIN_ID BETWEEN 1000000 AND 9999999)
);
